#!/usr/bin/env bash
# SCP wrapper script - uses deployment-specific known_hosts
# Generated by Terraform - Exercise 24 (uses DNS hostname)

GEN_DIR=$(dirname "$0")/../gen

if [ $# -lt 2 ]; then
   echo "usage: .../bin/scp ... ${devopsUsername}@${hostname} ..."
else
   scp -o UserKnownHostsFile="$GEN_DIR/known_hosts" "$@"
fi

# end of script
