#!/bin/bash
# setup.sh - Interactive setup for Terraform environment
# Usage: ./setup.sh [exercise-name]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_header() {
    echo -e "\n${BLUE}═══════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}\n"
}

prompt_value() {
    local var_name="$1"
    local description="$2"
    local default="$3"
    local is_secret="$4"
    
    echo -e "${YELLOW}$description${NC}"
    if [[ -n "$default" && "$default" != "replace-me" ]]; then
        echo -e "  Default: ${GREEN}$default${NC}"
        read -p "  Enter value (or press Enter for default): " value
        value="${value:-$default}"
    else
        if [[ "$is_secret" == "true" ]]; then
            read -sp "  Enter value: " value
            echo
        else
            read -p "  Enter value: " value
        fi
    fi
    echo "$value"
}

setup_env() {
    print_header "Setting up .env file"
    
    if [[ -f "$ENV_FILE" ]]; then
        echo -e "${YELLOW}Warning: .env already exists${NC}"
        read -p "Overwrite? (y/N): " overwrite
        if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
            echo "Skipping .env setup"
            return
        fi
    fi
    
    echo -e "${GREEN}Creating .env from template...${NC}\n"
    
    # Prompt for values
    echo -e "${BLUE}[1/4] Hetzner Cloud API Token${NC}"
    echo "  Get from: https://console.hetzner.cloud/"
    read -sp "  Enter token: " hcloud_token
    echo
    
    echo -e "\n${BLUE}[2/4] Primary SSH Public Key${NC}"
    echo "  Example: ssh-ed25519 AAAA... user@host"
    if [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
        default_ssh=$(cat "$HOME/.ssh/id_ed25519.pub")
        echo -e "  ${GREEN}Found: ~/.ssh/id_ed25519.pub${NC}"
        read -p "  Use this key? (Y/n): " use_default
        if [[ "$use_default" != "n" && "$use_default" != "N" ]]; then
            ssh_key="$default_ssh"
        else
            read -p "  Enter SSH public key: " ssh_key
        fi
    elif [[ -f "$HOME/.ssh/id_rsa.pub" ]]; then
        default_ssh=$(cat "$HOME/.ssh/id_rsa.pub")
        echo -e "  ${GREEN}Found: ~/.ssh/id_rsa.pub${NC}"
        read -p "  Use this key? (Y/n): " use_default
        if [[ "$use_default" != "n" && "$use_default" != "N" ]]; then
            ssh_key="$default_ssh"
        else
            read -p "  Enter SSH public key: " ssh_key
        fi
    else
        read -p "  Enter SSH public key: " ssh_key
    fi
    
    echo -e "\n${BLUE}[3/4] Secondary SSH Public Key (optional)${NC}"
    read -p "  Enter key (or press Enter to skip): " ssh_key_secondary
    
    echo -e "\n${BLUE}[4/4] HDM DNS Secret (optional, for DNS exercises)${NC}"
    echo "  Get from your dnsupdate.sec file"
    read -sp "  Enter secret (or press Enter to skip): " dns_secret
    echo
    
    # Write .env file
    cat > "$ENV_FILE" << EOF
# Environment variables for Terraform
# Generated by setup.sh on $(date)
# DO NOT commit this file to git!

# Provider Authentication
export HCLOUD_TOKEN="$hcloud_token"

# Terraform Variables
export TF_VAR_ssh_public_key="$ssh_key"
export TF_VAR_ssh_public_key_secondary="${ssh_key_secondary:-}"
export TF_VAR_dns_secret="${dns_secret:-}"
EOF
    
    chmod 600 "$ENV_FILE"
    echo -e "\n${GREEN}✓ Created $ENV_FILE${NC}"
    echo -e "${YELLOW}  Remember to run: source terraform/.env${NC}"
}

setup_exercise() {
    local exercise="$1"
    local exercise_dir="$SCRIPT_DIR/$exercise"
    local tfvars_example="$exercise_dir/config.auto.tfvars.example"
    local tfvars_file="$exercise_dir/config.auto.tfvars"
    
    if [[ ! -d "$exercise_dir" ]]; then
        echo -e "${RED}Error: Exercise directory not found: $exercise_dir${NC}"
        echo "Available exercises:"
        ls -d "$SCRIPT_DIR"/exercise-* "$SCRIPT_DIR"/base 2>/dev/null | xargs -n1 basename
        exit 1
    fi
    
    if [[ ! -f "$tfvars_example" ]]; then
        echo -e "${YELLOW}No config.auto.tfvars.example found for $exercise${NC}"
        return
    fi
    
    print_header "Setting up $exercise"
    
    if [[ -f "$tfvars_file" ]]; then
        echo -e "${YELLOW}Warning: config.auto.tfvars already exists${NC}"
        read -p "Overwrite? (y/N): " overwrite
        if [[ "$overwrite" != "y" && "$overwrite" != "Y" ]]; then
            echo "Skipping exercise setup"
            return
        fi
    fi
    
    echo -e "${GREEN}Creating config.auto.tfvars from example...${NC}"
    echo -e "${YELLOW}Press Enter to accept default values in [brackets]${NC}\n"
    
    # Parse example file and prompt for each variable
    local output=""
    while IFS= read -r line || [[ -n "$line" ]]; do
        # Keep comments and empty lines as-is
        if [[ "$line" =~ ^[[:space:]]*# ]] || [[ -z "${line// }" ]]; then
            output+="$line"$'\n'
            continue
        fi
        
        # Parse: key = "value" or key = value or key = [list]
        if [[ "$line" =~ ^([a-zA-Z_][a-zA-Z0-9_]*)[[:space:]]*=[[:space:]]*(.+)$ ]]; then
            local key="${BASH_REMATCH[1]}"
            local raw_value="${BASH_REMATCH[2]}"
            
            # For lists, keep the raw value (with internal quotes)
            # For strings, strip outer quotes for display
            if [[ "$raw_value" =~ ^\[.*\]$ ]]; then
                local default="$raw_value"
            else
                # Remove outer quotes only
                local default="${raw_value#\"}"
                default="${default%\"}"
            fi
            
            echo -e "${BLUE}$key${NC}"
            read -p "  Enter value [$default]: " value < /dev/tty
            value="${value:-$default}"
            
            # Output: don't quote numbers, booleans, or lists
            if [[ "$value" =~ ^[0-9]+$ ]] || [[ "$value" =~ ^(true|false)$ ]] || [[ "$value" =~ ^\[.*\]$ ]]; then
                output+="$key = $value"$'\n'
            else
                output+="$key = \"$value\""$'\n'
            fi
        else
            output+="$line"$'\n'
        fi
    done < "$tfvars_example"
    
    # Write output file
    echo -n "$output" > "$tfvars_file"
    echo -e "\n${GREEN}✓ Created $tfvars_file${NC}"
}

# Main
main() {
    echo -e "${GREEN}"
    echo "  ╔═══════════════════════════════════════╗"
    echo "  ║     Terraform Environment Setup       ║"
    echo "  ╚═══════════════════════════════════════╝"
    echo -e "${NC}"
    
    # Always offer to setup .env first
    if [[ ! -f "$ENV_FILE" ]]; then
        setup_env
    else
        echo -e "${GREEN}✓ .env file exists${NC}"
        read -p "Re-configure .env? (y/N): " reconfig
        if [[ "$reconfig" == "y" || "$reconfig" == "Y" ]]; then
            setup_env
        fi
    fi
    
    # If exercise specified, set it up
    if [[ -n "$1" ]]; then
        setup_exercise "$1"
    else
        echo -e "\n${YELLOW}Tip: Run with exercise name to also setup config.auto.tfvars${NC}"
        echo "  Example: ./setup.sh exercise-14-nginx"
    fi
    
    echo -e "\n${GREEN}Done!${NC}"
}

main "$@"
