#!/usr/bin/env bash
# SSH wrapper script - uses deployment-specific known_hosts
# Generated by Terraform

GEN_DIR=$(dirname "$0")/../gen

ssh -o UserKnownHostsFile="$GEN_DIR/known_hosts" ${devopsUsername}@${ip} "$@"

# end of script
